# configuration

[monday]


[monday.config]
mode = "Limit"
hard_limit_mwh = 180.21
hour_budget = 9

[monday.config.mask]
mode = "AlwaysOn"

[tuesday]

[tuesday.config]
mode = "AlwaysOn"

[wednesday]

[thursday]

[friday]

[saturday]
hours_always_on = [12, 13, 14, 15]

[sunday]
