[package]
name = "kiel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6"
reqwest = {version = "0.11.9", features = ["blocking"]}
thirtyfour = "0.28"
tokio = "1.17"
chrono-tz = "0.6"
rust_decimal = "1.22"